<?php

function reArrayFiles(&$file_post) {
    $file_ary = array();
    $file_count = count($file_post['name']);
    $file_keys = array_keys($file_post);

    for ($i=0; $i<$file_count; $i++) {
        foreach ($file_keys as $key) {
            $file_ary[$i][$key] = $file_post[$key][$i];
        }
    }
    return $file_ary;
}

function ucm_file_upload_help($path, $arg){
    if($path == 'admin/help#ucm_file_upload'){
        return t('UCM file upload module');
    }
}

function ucm_file_upload_menu(){
    $items = array();
    $items['fileupload'] = array(
        'title'=> 'File Upload',
        'description' => 'Upload files',
        'page callback' => 'drupal_get_form',
        'page arguments' => array('ucm_file_upload_form'),
        'access arguments' => array('upload files'),
        'type' => MENU_CALLBACK,
    );
    drupal_set_title('File Upload') ;
    return $items;
    
}

function ucm_file_upload_form($form, &$form_state){
    $form['file1'] = array(
       '#name' => 'files[]',
       '#type' => 'file',
       '#title' => t('Choose the file to upload'),
       '#size' => 22,
       '#description' => t('Upload a file to the public directory'),
    );
    
    $form['file2'] = array(
       '#name' => 'files[]',
       '#type' => 'file',
       '#title' => t('Choose the file to upload'),
       '#size' => 22,
       '#description' => t('Upload a file to the public directory'),
    );
    
    $form['file3'] = array(
       '#name' => 'files[]',
       '#type' => 'file',
       '#title' => t('Choose the file to upload'),
       '#size' => 22,
       '#description' => t('Upload a file to the public directory'),
    );
    
    $form['submit'] = array(
       '#type' => 'submit',
        '#value' => t('Upload files'),
        '#submit' => array('ucm_file_upload_submit'),
        );
        drupal_set_title('File Upload') ;
    return $form;
}

function ucm_file_upload_submit($form, &$form_state){
    $message = "";
    $base_path = drupal_realpath("public://");
    $allowedExts = array("gif", "jpeg", "jpg", "png", "pdf", "doc", "docx");
    //IF THE FILES ARRAY EXISTS, CONVERT IT TO A NICER ARRAY FORMAT
    if ($_FILES['files']){
        $files = reArrayFiles($_FILES['files']);
    }else{
        $message = "No file uploaded<br/>";
        drupal_set_message($message);
        return;
    }
    //LOOP THROUGH EACH FILE, VALIDATE IT, SAVE IT
    foreach($files as $file){
       $extension = end(explode(".", $file['name']));
       if ((($file["type"] == "image/gif")
       || ($file["type"] == "image/jpeg")
       || ($file["type"] == "image/jpg")
       || ($file["type"] == "image/png"))
       && ($file["size"] < 10000000)
       && in_array($extension, $allowedExts))
      {
      if ($file["error"] > 0)
        {
        $message .= "Return Code: " . $file["error"] . "<br/>";
        }//end of error if block
      else
        {
        if (file_exists($base_path . "/files/" . $file["name"]))
          {
          $message .= $file["name"] . " already exists. <br/>";
          }//end of file_exists if block
        else
          {
          move_uploaded_file($file["tmp_name"], $base_path . "/" . $file["name"]);
          $message .= "Stored in: /files/" . $file["name"] . "<br/>";
          }//end of file_exists else block
        }//end of error else block
      }//end of MIME if block
    else
      {
      $message .= "Invalid file<br/>";
      }
    }//end of foreach block
    drupal_set_message($message);
}

function ucm_file_upload_permission(){
    return array('upload files' => array(
     'title' => t('Upload files'),
     'description' => t('Allows users to upload arbitrary files to the public files directory.'),   
    )
    );
}

/**
 * Implements hook_user_default_permissions().
 */
function ucm_file_upload_user_default_permissions() {
  $permissions = array();

  // Exported permission: upload files.
  $permissions['upload files'] = array(
    'name' => 'upload files',
    'roles' => array(
      0 => 'administrator',
      1 => 'site manager',
    ),
    'module' => 'ucm_file_upload',
  );

  return $permissions;
}
